## Libraries import

In [1]:
import pandas as pd
import numpy as np
import os
import glob

# functions and libraires from competition github
from dataclasses import dataclass
from io_f import read_data_file
from visualize_f import visualize_heatmap, visualize_trajectory

In [2]:
def findFilesSpecificFormat(searchDirectory, fileExtension):
    fileExtension = f"*.{fileExtension}"
    matchingFileFormatList = [file
                             for path, subdir, files in os.walk(searchDirectory)
                             for file in glob.glob(os.path.join(path, fileExtension))]
    return matchingFileFormatList

In [3]:
refFeatureFiles = sorted(findFilesSpecificFormat("referencePublicNotebooks/1000Features/train/", "csv"))
ownFeatureFiles = sorted(findFilesSpecificFormat("referencePublicNotebooks/1000_dtFeatures/", "csv"))

In [4]:
refFeatureFiles[0:3], ownFeatureFiles[0:3]

(['referencePublicNotebooks/1000Features/train/5a0546857ecc773753327266_1000_train.csv',
  'referencePublicNotebooks/1000Features/train/5c3c44b80379370013e0fd2b_1000_train.csv',
  'referencePublicNotebooks/1000Features/train/5d27075f03f801723c2e360f_1000_train.csv'],
 ['referencePublicNotebooks/1000_dtFeatures/5a0546857ecc773753327266_dtFeat_1000_train.csv',
  'referencePublicNotebooks/1000_dtFeatures/5c3c44b80379370013e0fd2b_dtFeat_1000_train.csv',
  'referencePublicNotebooks/1000_dtFeatures/5d27075f03f801723c2e360f_dtFeat_1000_train.csv'])

In [5]:
refDf = pd.read_csv(refFeatureFiles[0])

In [6]:
refDf.shape

(9296, 946)

In [7]:
ownDf = pd.read_csv(ownFeatureFiles[0])

In [8]:
ownDf.shape

(9296, 1887)

In [16]:
refDfColumns = refDf.columns.values.tolist()[1:-4]
ownDfColumns = ownDf.columns.values.tolist()[1:-4]

In [17]:
print(len(refDfColumns))

941


In [18]:
print(len(ownDfColumns))

1882

In [44]:
numCommonFeatures = len(refDfColumns)

In [42]:
# ensures columns are in right order
np.array_equal(np.array(refDfColumns), np.array(ownDfColumns[0:941]))

True

In [43]:
# all reference columns are in own df
set(refDfColumns) - set(ownDfColumns)

set()

In [45]:
refData = refDf.iloc[:,0:numCommonFeatures].to_numpy()

In [46]:
refData.shape

(9296, 941)

In [47]:
ownData = ownDf.iloc[:,0:numCommonFeatures].to_numpy()

In [48]:
ownData.shape

(9296, 941)

In [49]:
np.array_equal(refData, ownData)

False

In [32]:
ownData[0,:] < 

array([-999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999,  -77, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
        -82, -999, -999, -999, -999, -999, -999,  -91, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999,  -87, -999,
       -999,  -76, -999, -999, -999, -999,  -76, -999, -999, -999, -999,
       -999, -999, -999, -999, -999,  -82, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -9

In [54]:
refData[0,np.where(refData[0,:] > -900)[0]]

array([  4, -78, -90, -84, -88, -89, -90, -86, -84, -87, -85, -86, -84])

In [55]:
ownData[0,np.where(ownData[0,0:941] > -900)[0]]

array([  4, -77, -82, -91, -87, -76, -76, -82, -86, -77, -82, -43, -86,
       -80, -83, -82, -81, -87, -74, -63, -82, -82, -82, -80, -90, -87,
       -90, -86, -77, -76, -82, -86, -86, -92, -76, -85, -88, -82, -88,
       -77, -86])